apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  namespace: login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      serviceAccountName: jenkins-deployer
      containers:
      - name: login-app
        image: wiyuwarwoyo/login-app2:latest   # akan di-patch Jenkins
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
