apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: login-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
  namespace: login-app
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch","create","update","patch"]
- apiGroups: [""]
  resources: ["services","pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
  namespace: login-app
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: login-app
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io
