apiVersion: v1
kind: Service
metadata:
  name: login-app
  namespace: login-app
spec:
  type: NodePort          # ganti Ingress kalau mau
  selector:
    app: login-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32080
